import random
#introduction
print("You have to guess the three numbers generated by the AI, you have 10 tries!! to win the game 1.) after players_guessing, if the AI returns your result. Listen closely!!!\n i.) if you see the word PICO it means your number is correct BUT in the wrong position\n ii.) if you see the word MACO is means the number is tottally wrong  and not among the corrct answers \n iii.) if you see the word BIEN it means the number is correct and in the right position \n iv.) remember all 3 number have to be correct to win the GRAND price \n GOODLUCK PLAYING!!!")


list = ["0","1","2","3","4","5","6","7","8","9"]
ai_vals=[]
result_val=["PICO","MACO","BEIN"]
Dlist=[]


def comparing(player_val):
        if player_val[0] in ai_vals:
            if player_val[0] is ai_vals[0]:
                return result_val[2]
            else:
                return result_val[0]
        else:
            return result_val[1]

def comparing1(player_val):
    if player_val[1] in ai_vals:
        if player_val[1] is ai_vals[1]:
            return result_val[2]
        else:
            return result_val[0]
    else:
        return result_val[1]

def comparing2(player_val):
    if player_val[2] in ai_vals:
        if player_val[2] is ai_vals[2]:
            return result_val[2]
        else:
            return result_val[0]
    else:
        return result_val[1]


def validate_playernum():
    player_val=[]
    players_guess = input("enter your 3 numbers:")
    if len(players_guess) == 3 :
       if players_guess[0] in list:
           player_val.append(players_guess[0])
           if players_guess[1] in list:
               player_val.append(players_guess[1])
               if players_guess[2] in list:
                   player_val.append(players_guess[2])
                   print(player_val)
                   comparing(player_val)
                   comparing1(player_val)
                   comparing2(player_val)
                   print(comparing(player_val),comparing1(player_val),comparing2(player_val))
                   return player_val
               else:
                   return print("your third players_guess is not a number")
           else:
               return print("your second players_guess is not a number")
       else:
           return print("your first players_guess is not a number")
    else:
        return print(",you just lost one of your ten chances and read instruction properly")
    return player_val
        
def get_random():
    val1 = str(random.random() * 10)
    ai_1 = val1[0]
    val2 = str(random.random() * 10)
    ai_2 = val2[0]
    val3 = str(random.random() * 10)
    ai_3 = val3[0]
    ai_vals.append(ai_1)
    ai_vals.append(ai_2)
    ai_vals.append(ai_3)
    return ai_vals
    
get_random()




count = 0 
for x in range(1,13):
    if count <= 10 :
        validate_playernum()
        count+=1
        print (count)
    else:
       print("nice try!!")
  
    
